
spring:
  # Database config
  datasource:
    driver-class-name: org.h2.Driver
    username: test
    password: test
    url: jdbc:h2:file:./data;AUTO_SERVER=TRUE
    hikari:
      jdbc-url: jdbc:h2:file:./data;AUTO_SERVER=TRUE
      connection-test-query: SELECT 1
  jpa:
    hibernate:
      ddlAuto: create-drop #for testing purposes
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        globally_quoted_identifiers: true
    open-in-view: true
server:
  port: 80
